Add minimal documentation to CGP framework
contextgeneric/cgp pull request #46
Opened 2024-12-29 08:40 UTC by marvin-hansen

Addresses issue #45

Add detailed Rust documentation across multiple CGP crates:

cgp-component-macro:
- Document all procedural macros with examples
- Improve type parameter naming conventions
- Add clear usage patterns and best practices

cgp-field:
- Document core traits and type system
- Add field access and manipulation examples
- Improve type-level documentation

cgp-field-macro-lib:
- Document internal macro implementations
- Add type construction patterns
- Provide detailed expansion examples

All documentation follows Rust best practices including:
- Clear descriptions and examples
- Proper cross-references
- Type parameter documentation
- Implementation notes

Changes are documentation-only, improving code clarity without
modifying functionality.

2025-01-05 20:27 UTC, soareschen requested changes
@marvin-hansen I just saw your pull request. Thanks a lot on the effort you put in to help document the crate!

I have looked through some of your documentation, however it seems like there are quite a number of misunderstanding on the use of the constructs, especially when they are not yet covered by the book that I am writing. Also, the PR is pretty large and can be challenging to discuss and approve everything together.

I'd suggest that you break down the pull requests by topics covered by each chapter in the book. As for the constructs that are not yet covered by the book, I think it might be better if you hold off the documentation until the relevant chapter is ready.

2025-01-05 20:27 UTC, soareschen commented on crates/cgp-component/src/types/use_delegate.rs
> +/// macro, which handles the delegation implementation details automatically.
We have just covered the use of `UseDelegate` in the new chapter for error raiser delegation: https://patterns.contextgeneric.dev/delegated-error-raiser.html

We don't really use `UseDelegate` as values inside the context fields.

2025-01-05 20:27 UTC, soareschen commented on crates/cgp-component/src/types/with_provider.rs
> +/// core implementation.
The `WithProvider` patttern is actually a kind of cross-trait delegation pattern, where the provider implementation of one trait is delegated to the provider of a different trait.

An example is the type traits, which can delegate the provider to the `ProvideType` provider trait as follows:

```rust
#[cgp_component {
    name: RuntimeTypeComponent,
    provider: ProvideRuntimeType,
}]
pub trait HasRuntimeType {
    type Runtime;
}

impl<Context, Provider, Runtime> ProvideRuntimeType<Context> for WithProvider<Provider>
where
    Provider: ProvideType<RuntimeTypeComponent, Type = Runtime>,
{
    type Runtime = Runtime;
}
```

We will only cover the use of `WithProvider` at a later chapter.

2025-01-05 20:27 UTC, soareschen commented on crates/cgp-field-macro/src/lib.rs
> +/// let name = person.get_field(field!(name));
The argument for `get_field` is the `PhantomData` of the field name symbol. i.e. `person.get_field(PhantomData::<symbol!("name")>)`. We usually only need to provide the unqualified `PhantomData` as the argument, if it is used in generic impls where only one instance of `HasField` is visible.

2025-01-05 20:27 UTC, soareschen commented on crates/cgp-field-macro/src/lib.rs
> +/// let age_symbol = symbol!(age);
The `symbol!` macro is a way to lift string values to the type level. So something like `symbol!("foo")` is a *type* that uniquely represents the string `"foo"`.

2025-01-05 20:27 UTC, soareschen commented on crates/cgp-field-macro/src/lib.rs
> +/// Product! {
The `Product!` macro generates anonymous structs as type-level lists. So something like `Product![String, u32, bool]` is desugared to `Cons<String, Cons<u32, Cons<bool, Nil>>>`.

2025-01-05 20:27 UTC, soareschen commented on crates/cgp-field-macro/src/lib.rs
> +/// }
The `Sum!` macro is similar to `Product!` that it generates anonymous sum types. So something like `Sum![String, u32, bool]` is desugared to `Either<String, Either<u32, Either<bool, Void>>>`.

2025-01-05 20:27 UTC, soareschen commented on crates/cgp-field-macro/src/lib.rs
> +/// ```
The `product!` macro is used for value-level pattern matching and construction of product values. So something like `product![foo, bar, baz]` is desugared to `Cons(foo, Cons(bar, Cons(baz, Nil)))`.

2025-01-05 20:27 UTC, soareschen commented on crates/cgp-field/src/impls/use_field.rs
> +/// ```
The `UseField` pattern is used for implementing getter traits using `HasField`. Something like:

```rust
#[cgp_component {
    provider: NameGetter,
}]
pub trait HasName {
    fn get_name(&self) -> &String;
}

impl<Context, Tag> NameGetter<Context> for UseField<Tag>
where
    Context: HasField<Tag, Value = String>,
{
    fn get_name(context: &Context) -> &String {
        context.get_field(PhantomData)
    }
}

pub type GetNameFromNameField = UseField<symbol!("name")>;
```

We will cover the pattern in later chapters of the book.

2025-01-06 03:45 UTC, marvin-hansen commented
No problem. 

I close this PR for good, and then gradually re-submit one crate at a time with the docs and your suggestions and probably add applicable references to the book


> @marvin-hansen I just saw your pull request. Thanks a lot on the effort you put in to help document the crate!
> 
> I have looked through some of your documentation, however it seems like there are quite a number of misunderstanding on the use of the constructs, especially when they are not yet covered by the book that I am writing. Also, the PR is pretty large and can be challenging to discuss and approve everything together.
> 
> I'd suggest that you break down the pull requests by topics covered by each chapter in the book. As for the constructs that are not yet covered by the book, I think it might be better if you hold off the documentation until the relevant chapter is ready.

2025-01-06 03:45 UTC, closed without merging